server:
  port: 8081

spring:
  application:
    name: trainer-workload-service

  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/workloaddb}

  data:
    mongodb:
      auto-index-creation: true

  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}?jms.redeliveryPolicy.maximumRedeliveries=3&jms.redeliveryPolicy.initialRedeliveryDelay=1000&jms.redeliveryPolicy.redeliveryDelay=2000&jms.redeliveryPolicy.useExponentialBackOff=true
    user: ${ACTIVEMQ_USER:admin}
    password: ${ACTIVEMQ_PASSWORD:admin}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
