spring:
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://activemq:61616}
  mongodb:
    uri: ${MONGODB_URI:mongodb://mongodb:27017/workloaddb}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
